// Actions for MapPage
export const GET_OLD_ROUTE = "GET_OLD_ROUTE";

export const REQUEST_ALL_PATIENTS = "REQUEST_ALL_PATIENTS";
export const RECEIVE_ALL_PATIENTS = "RECEIVE_ALL_PATIENTS";
export const CLEAR_EDIT_PATIENT = "CLEAR_EDIT_PATIENT";
export const EDIT_PATIENT = "EDIT_PATIENT";
export const EDIT_PATIENT_SUCCESS = "EDIT_PATIENT_SUCCESS";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const CREATE_PATIENT = "CREATE_PATIENT";
export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";
export const TOGGLE_FORM_MAP = "TOGGLE_FORM_MAP";
export const SHOW_FORM_MAP = "SHOW_FORM_MAP";
export const CLOSE_FORM_MAP = "CLOSE_FORM_MAP";

// LOGIN
export const LOGIN_REQUESTING = "LOGIN_REQUESTING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const CHECK_IS_LOGIN = "CHECK_IS_LOGIN";

// LOGOUT
export const LOGOUT_REQUESTING = "LOGOUT_REQUESTING";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// ACTIONS FOR QUIZADMIN
export const REQUEST_ALL_QUIZ = "REQUEST_ALL_QUIZ";
export const RECEIVE_ALL_QUIZ = "RECEIVE_ALL_QUIZ";
export const CLEAR_EDIT_QUIZ = "CLEAR_EDIT_QUIZ";
export const CREATE_QUIZ = "CREATE_QUIZ";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const EDIT_QUIZ = "EDIT_QUIZ";
export const EDIT_QUIZ_SUCCESS = "EDIT_QUIZ_SUCCESS";
export const UPDATE_QUIZ = "UPDATE_QUIZ";
export const UPDATE_QUIZ_SUCCESS = "UPDATE_QUIZ_SUCCESS";
export const DELETE_QUIZ = "DELETE_QUIZ";
export const DELETE_QUIZ_SUCCESS = "DELETE_QUIZ_SUCCESS";
